In [1]:
include("RDMM.jl")
using LinearAlgebra
using Random
using DelimitedFiles
using BenchmarkTools

In [2]:
Random.seed!(1);

In [3]:
n = 90
N = 463715
y = []
A = zeros(N,n)
workers = 8

open("YearPredictionMSD.dat") do dataFile
    i = 1
    while ! eof(dataFile)
        line = readline(dataFile)
        elms = split(line,' ')
        
        push!(y,parse(Float64,elms[1]))
        for j=2:size(elms,1)
            if elms[j] != ""
                sparse = split(elms[j],':')
                A[i,parse(Int,sparse[1])] = parse(Float64,sparse[2])
            end
        end
        i += 1
    end
end
y = real(y);

In [4]:
x2,lam = @btime rdmm_ls(A,y,workers,rflag=false)

  354.248 ms (340 allocations: 650.33 MiB)


90×1 Matrix{Float64}:
 37.29653384394671
 -1.6404384980523208
 -0.05584237131292724
 -0.02092802614934186
 -0.47912534310934696
 -4.429128917191587
 -2.353867695009722
 -0.0799266809915209
 -2.541766632987297
  2.2246692070312477
 -7.774672805270129
  3.5875183209872343
  1.150444089494913
  ⋮
  0.039454997398193914
 -0.004689270067582241
  0.5101041702376179
 -0.03339465298329136
 -0.08795651592589349
 -0.05938005947140637
 -0.40013430579700027
  0.10656944618136521
  0.009497169157296814
  1.0029829909494872
 -0.009240521354394467
  0.03125450244328798

In [5]:
x3,lam = @btime rdmm_ls(A,y,workers)

  2.366 s (453 allocations: 1.27 GiB)


90×1 Matrix{Float64}:
 37.3196232326151
 -1.6440195181055794
 -0.05695186588473078
 -0.019892271013745244
 -0.4746169484153002
 -4.415592077031572
 -2.363080873159099
 -0.03441502327500423
 -2.5546030376936244
  2.2604753689940935
 -7.759959533053802
  3.5937089563731917
  1.1510817204187092
  ⋮
  0.039440050838383645
 -0.00470072493503404
  0.5122049288845907
 -0.0333655110367761
 -0.0868554235746889
 -0.059816608441688235
 -0.4067432343551809
  0.10593478139150103
  0.009554686050919178
  1.0076337474004724
 -0.00888466183937946
  0.028015556541066564

In [6]:
x1 = @btime A\y

  2.657 s (567 allocations: 322.20 MiB)


90-element Vector{Float64}:
 37.31988549991181
 -1.6442108406849085
 -0.05741080714922644
 -0.01814622045988183
 -0.47501221151317835
 -4.416818026168529
 -2.3644614223173988
 -0.03290520828989307
 -2.5565304068483377
  2.2585129014131398
 -7.766192954882031
  3.5947570040459644
  1.1503668438259116
  ⋮
  0.03953089795270607
 -0.0046675660948518275
  0.5127041952626832
 -0.03331738254930598
 -0.08667893003614416
 -0.05984078335229915
 -0.4064278445328816
  0.10589249564732504
  0.009486588384810814
  1.0066031910184399
 -0.008952057118286142
  0.028463754649159883